CRCCountryCohort <- rownames(combined_short_metadata_2[combined_short_metadata_2$country %in% droplevels(combined_short_metadata_2[CRCIndividuals,"country"]),])
AdenomaCountryCohort <- rownames(combined_short_metadata_2[combined_short_metadata_2$country %in% droplevels(combined_short_metadata_2[AdenomaIndividuals,"country"]),])
#T2DCountryCohort <- rownames(combined_short_metadata_2[combined_short_metadata_2$country %in% droplevels(combined_short_metadata_2[T2DIndividuals,"country"]),])
CirrhosisCountryCohort <- rownames(combined_short_metadata_2[combined_short_metadata_2$country %in% droplevels(combined_short_metadata_2[CirrhosisIndividuals,"country"]),])
IBDCountryCohort <- rownames(combined_short_metadata_2[combined_short_metadata_2$country %in% droplevels(combined_short_metadata_2[IBDIndividuals,"country"]),])
T2DCountryCohort <- c(intersect(c(Young,Middle),AsiaIndividuals),intersect(Elderly,c(AllEUIndividuals,AsiaIndividuals)))


rfCirrhosisElderly_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,CirrhosisCountryCohort),intersect(Young,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisElderly_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,CirrhosisCountryCohort),intersect(Middle,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisElderly_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,CirrhosisCountryCohort),intersect(Elderly,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisMiddle_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,CirrhosisCountryCohort),intersect(Young,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisMiddle_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,CirrhosisCountryCohort),intersect(Middle,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisMiddle_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,CirrhosisCountryCohort),intersect(Elderly,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisYoung_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,CirrhosisCountryCohort),intersect(Young,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisYoung_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,CirrhosisCountryCohort),intersect(Middle,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)
rfCirrhosisYoung_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,CirrhosisCountryCohort),intersect(Elderly,CirrhosisCountryCohort),CirrhosisIndividuals,SelectControls,100,10,9)

rfIBDElderly_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,IBDCountryCohort),intersect(Young,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDElderly_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,IBDCountryCohort),intersect(Middle,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDElderly_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,IBDCountryCohort),intersect(Elderly,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDMiddle_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,IBDCountryCohort),intersect(Young,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDMiddle_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,IBDCountryCohort),intersect(Middle,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDMiddle_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,IBDCountryCohort),intersect(Elderly,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDYoung_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,IBDCountryCohort),intersect(Young,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDYoung_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,IBDCountryCohort),intersect(Middle,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)
rfIBDYoung_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,IBDCountryCohort),intersect(Elderly,IBDCountryCohort),IBDIndividuals,SelectControls,100,27,26)

rfT2DElderly_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,T2DCountryCohort),intersect(Young,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DElderly_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,T2DCountryCohort),intersect(Middle,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DElderly_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,T2DCountryCohort),intersect(Elderly,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DMiddle_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,T2DCountryCohort),intersect(Young,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DMiddle_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,T2DCountryCohort),intersect(Middle,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DMiddle_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Middle,T2DCountryCohort),intersect(Elderly,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DYoung_Young <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,T2DCountryCohort),intersect(Young,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DYoung_Middle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,T2DCountryCohort),intersect(Middle,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)
rfT2DYoung_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Young,T2DCountryCohort),intersect(Elderly,T2DCountryCohort),T2DIndividuals,SelectControls,100,14,13)

rfCRCElderly_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,CRCCountryCohort),intersect(c(Elderly),CRCCountryCohort),CRCIndividuals,SelectControls,100,23,22)
rfCRCElderly_YoungMiddle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,CRCCountryCohort),intersect(c(Young,Middle),CRCCountryCohort),CRCIndividuals,SelectControls,100,23,22)
rfCRCYoungMiddle_YoungMiddle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(c(Young,Middle),CRCCountryCohort),intersect(c(Young,Middle),CRCCountryCohort),CRCIndividuals,SelectControls,100,23,22)
rfCRCYoungMiddle_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(c(Young,Middle),CRCCountryCohort),intersect(Elderly,CRCCountryCohort),CRCIndividuals,SelectControls,100,23,22)

rfAdenomaElderly_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,AdenomaCountryCohort),intersect(c(Elderly),AdenomaCountryCohort),AdenomaIndividuals,SelectControls,100,11,10)
rfAdenomaElderly_YoungMiddle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(Elderly,AdenomaCountryCohort),intersect(c(Young,Middle),AdenomaCountryCohort),AdenomaIndividuals,SelectControls,100,11,10)
rfAdenomaYoungMiddle_YoungMiddle <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(c(Young,Middle),AdenomaCountryCohort),intersect(c(Young,Middle),AdenomaCountryCohort),AdenomaIndividuals,SelectControls,100,11,10)
rfAdenomaYoungMiddle_Elderly <- iterative_rf_fixed_size(combined_species_profile_with_age_country_final[,core_species],intersect(c(Young,Middle),AdenomaCountryCohort),intersect(Elderly,AdenomaCountryCohort),AdenomaIndividuals,SelectControls,100,11,10)


